return {
	clipboard = "unnamedplus",
	inccommand = "nosplit",
	signcolumn = "number",
	mouse = "a",
	showmode = false,
	swapfile = false,
	hlsearch = false,
	backup = false,
	ruler = false,
	termguicolors = true,
	splitbelow = true,
	cursorline = true,
	breakindent = true,
	cmdheight = 0,
	numberwidth = 1,
	laststatus = 3,
	scrolloff = 4,
	sidescrolloff = 8,
	updatetime = 300,
}
